apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: person-db
  name: person-db
spec:
  replicas: 0
  selector:
    matchLabels:
      app: person-db
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: person-db
    spec:
      containers:
      - image: docker.io/postgres:16
        name: postgres