apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: person-db
  name: person-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-db
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: person-db
    spec:
      containers:
        - name: postgres
          image: docker.io/postgres:16
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: db
                  name: person-db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: person-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: person-db
