apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: person-pvc
  namespace: applications
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2
  volumeMode: Filesystem